### ISSUE TITLE
About gap extension decay 

### ISSUE THREAD

**Issue by SHuang-Broad** [mbreese/swalign#12]
Hi Marcus,

I'm wondering what the intuitions are behind the gap extension decay parameter?

In particular, I've noticed the use of that parameter is modeled as
```python
 min(0, self.gap_extension_penalty + ins_run * self.gap_extension_decay)
```
and similarly for deletions.

My guess is that this is to further discourage large gaps?
Is there a specific use scenario you had in mind for this model?

Thanks!
Steve

**Comment by mbreese** [comment]
The idea would be that for RNAseq data, you might want allow for the potential for skipping introns (or gaps). So that if you once you hit a deletion of a certain size, you might want to reduce the penalty.

So, for example, you might allow a deletion of 10bp, but after that, you’d have no penalty.

I’m not sure how practical it ends up being in practice though.

—
Marcus

**Comment by SHuang-Broad** [comment]
Ah, I see. I assumed it was for DNA.
Thanks for the quick answer!
Steve
